### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed (Hard Top Vanillaccurate 512x)

### ISSUE THREAD

**Issue by Shinzef** [ozelot379/ConvertJavaTextureToBedrock#28] opened 2020-11-27 12:29 UTC
**Describe the issue**
Please consult the readme before you report an issue

A clear and concise description of what the issue is.
well it errored

Is there an error message?
yes
Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?
same

Are the textures available/correct on Java version?
yes

**System info**

***Converting***
System OS: windows 10
Browser: Chrome

***Game***
System OS: Windows 10

**Texture pack**
Link to download: https://drive.google.com/file/d/1qhDqHZyj7Kwt2AkxfrLlPCo5UwNX4CTt/view

**Comment by ozelot379** [comment] 2020-11-27 15:05
@Shinzef 
Duplicate of https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/13 and https://github.com/ozelot379/ConvertJavaTextureToBedrock/issues/18

**Closed by ozelot379** 2020-11-27 15:05 UTC
